package com.kingtogroup.domain;

public class Product {
	public int RecordId = 1058;
	public int Oid = 738;
	public String StoreName;
	public String Logo;
	public int Uid = 117;
	public String Sid = "";
	public int Pid = 82;
	public String PSN = "";
	public int CateId = 81;
	public String Remark = "";
	public String MassagerNames = "任意推拿师 ";
	public String PServiceDate = "2015年10月20日";
	public String ServiceAddress = "无 ";
	public String ServiceTime;
	public int BrandId = 26;
	public int StoreId = 5;
	public int StoreCid = 15;
	public int StoreSTid = 7;
	public String Name = "太乙肩颈推拿";
	public String Massagers = "5";
	public String ShowImg = "ps_1508311452400952835.jpg";
	public int DiscountPrice = 78;
	public int ShopPrice = 78;
	public int CostPrice = 78;
	public int MarketPrice = 78;
	public int Weight = 45;
	public int IsReview = 0;
	public int RealCount = 1;
	public int BuyCount = 1;
	public int SendCount = 0;
	public int Type = 0;
	public int PayCredits = 0;
	public int CouponTypeId = 0;
	public int ExtCode1 = 0;
	public int ExtCode2 = 0;
	public int ExtCode3 = 0;
	public int ExtCode4 = 0;
	public int ExtCode5 = 0;
	public String AddTime = "2015-10-20T17:04:25";
	public int Woods = 0;
	public int Water = 0;
	public int Stsid = 0;
	public int Storerid = 0;
	public String ServiceDate = "2015-11-25T14:00:09.5154661+08:00";
	public String Consignee = "";
	public String Mobile = "";
	public String Address = "";
	public int Regionid = 2685;
	public int ServiceSelf = 1;
	public int Price_Grade1 = 0;
	public int Price_Grade2 = 0;
	public int Price_Grade3 = 0;
	public int Price_Grade4 = 0;
	public int TiCheng_Grade1 = 0;
	public int TiCheng_Grade2 = 0;
	public int TiCheng_Grade3 = 0;
	public int TiCheng_Grade4 = 0;
}
